# Generated by Django 4.1.7 on 2023-03-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_filter_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
